project:
  type: website

website:
  title: "BioGeoAI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

