project:
  type: website
  output-dir: _site

website:
  title: "BioGeoAI Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: PUBLICATIONS.qmd
        text: Publications
      - href: students.qmd
        text: Students

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
